package:
  name: rachis-cli
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
  entry_points:
  - rachis=rachis_cli.__main__:rachis
requirements:
  host:
  - python {{ python }}
  - pip
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - setuptools
  - click {{ click }}
  - rachis >={{ rachis }}
  - q2templates >={{ q2templates }}
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
  - rachis >={{ rachis }}
  - q2templates >={{ q2templates }}
  - pytest
  - pytest-xdist
  - q2-mystery-stew
  imports:
  - rachis_cli
  commands:
  - Q2CLIDEV=1 QIIMETEST= rachis --help
  - Q2CLIDEV=1 QIIMETEST= py.test --pyargs rachis_cli
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
