{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2cli
  version: {{ version }}

source:
  path: ../..

build:
  script: make install
  entry_points:
    - qiime=q2cli.__main__:qiime

requirements:
  host:
    - python  {{ python }}
    - setuptools

  run:
    - python  {{ python }}
    - pip
    - click >=7,<8
    - qiime2 {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - pytest

  imports:
    - q2cli

  commands:
    - QIIMETEST= qiime --help

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
